authors:
- m-dango

files:
  solution:
  - leap.ys
  test:
  - test/test-1.ys
  example:
  - .meta/leap.ys

blurb: Determine whether a given year is a leap year.

source: CodeRanch Cattle Drive, Assignment 3

source_url: https://coderanch.com/t/718816/Leap
